# Generated by Django 5.0.1 on 2024-02-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='imges/')),
                ('img_2', models.ImageField(upload_to='imges/')),
                ('baner_1', models.ImageField(upload_to='imges/')),
                ('baner_2', models.ImageField(upload_to='imges/')),
                ('takfif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
    ]
